=== apenfe/DAW_2_2425/marcas/tema_1/alumnos.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, edad)>
<!ATTLIST alumno
          dni CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== apenfe/DAW_2_2425/marcas/tema_1/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "file:/C:/Users/adria/Desktop/alumnos.dtd">
<alumnos>
<alumno dni="1234">
<nombre>adrian</nombre>
<edad>28</edad>
</alumno>
<alumno dni="1234">
<nombre>maria</nombre>
<edad>21</edad>
</alumno>
<alumno dni="1234">
<nombre>mario</nombre>
<edad>20</edad>
</alumno>
</alumnos>
