<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ediciones_aranda [
  <!ELEMENT ediciones_aranda (cabecera, informes)>
  <!ELEMENT cabecera (titulo, contenido, descripcion, fecha)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT contenido (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT fecha (#PCDATA)>
  <!ELEMENT informes (norte, centro, sur)>
  <!ELEMENT norte (trim1, trim2, trim3, trim4)>
  <!ELEMENT centro (trim1, trim2, trim3, trim4)>
  <!ELEMENT sur (trim1, trim2, trim3, trim4)>
  <!ELEMENT trim1 (#PCDATA)>
  <!ATTLIST trim1 valor CDATA "NO_INFO">
  <!ELEMENT trim2 (#PCDATA)>
  <!ATTLIST trim2 valor CDATA "NO_INFO">
  <!ELEMENT trim3 (#PCDATA)>
  <!ATTLIST trim3 valor CDATA "NO_INFO">
  <!ELEMENT trim4 (#PCDATA)>
  <!ATTLIST trim4 valor CDATA "NO_INFO">
]>
<ediciones_aranda>
  <cabecera>
    <titulo>Ediciones Aranda</titulo>
    <contenido>Informe regional de ventas</contenido>
    <descripcion>Informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>30/12/2009</fecha>
  </cabecera>
  <informes>
    <norte>
      <trim1>24000</trim1>
      <trim2>38600</trim2>
      <trim3 >NO_INFO</trim3>
      <trim4>NO_INFO</trim4>
    </norte>
    <centro>
      <trim1>NO_INFO</trim1>
      <trim2>16080</trim2>
      <trim3>25000</trim3>
      <trim4>29000</trim4>
    </centro>
    <sur>
      <trim1>27000</trim1>
      <trim2>31400</trim2>
      <trim3>40100</trim3>
      <trim4>30000</trim4>
    </sur>
  </informes>
</ediciones_aranda>